### ISSUE TITLE
How to run 

### ISSUE THREAD

**Issue by gugudexiatian** [spallas/time-attention#4]
hi, I have troubling running the code. How to run the code of the control experiments, such as how to produce result.csv and attn.csv, what commands should be used to implement them?
l am looking forward  from you.

**Comment by gugudexiatian** [comment]
hi, I just confused that how to make the attention layer not work? Is attn_result generated by itself or needs to be recorded? Looking forward to your reply.

**Comment by Angelogeb** [comment]
Hi @gugudexiatian,

In order to run the code for multiple configurations you have to perform the following steps
* Create a directory `base_configs/` containing the "base" configurations such as `conf/NASDAQ100.json`
* Execute `python generate_configs.py --src base_configs/ --dst gen_confs/` which will
  generate multiple configurations in the destination folder
* Execute `python gen_test.py` which will create `result.csv`

`attn.csv` was created manually.

Regarding the last question, if I understood correctly, you can disable each of the attention layers through the field `inp_att_enabled` and `temporal_att_enabled`.

**Comment by harukou** [comment]
Don't forget to install these modules:
`pip install cached-property`
`pip install dataclasses-json`

**Comment by gugudexiatian** [comment]
Thanks for the quick answers, thanks for the great code！！
